#!/bin/sh

# print vpnc version from file VERSION, appending the string printed
# by svnversion(1) if appropriate

_version="`cat VERSION`"

if [ -d .svn ]; then
		if command -v svnversion >/dev/null; then
				_version="$_version-`svnversion`"
		else
				_version="$_version-`grep -A1 '^dir$' .svn/entries | tail -n1`"
		fi
fi

echo "$_version"

exit 0
