#!/bin/sh

getvar () {
	if [ $# -ne 2 ]; then
		echo "Usage: $0 <parameter file> <variable name>" 1>&2
		return 1
	fi
	sed -n 's/^'"$2"' //p' "$1"
	return 0
}

fix_ip_get_output () {
	sed 's/cache//;s/metric[0-9]\+ [0-9]\+//g' | xargs echo
}

defr=/var/run/vpnc/defaultroute
gateway=/var/run/vpnc/gateway
pid=/var/run/vpnc/pid

if [ $# -ne 1 ]; then
	echo "Usage: $0 <parameter file>" 1>&2
	exit 1
fi

if [ -x "`which vpnc`" ]; then
	VPNC="`which vpnc`"
elif [ -x /usr/local/sbin/vpnc ]; then
	VPNC=/usr/sbin/vpnc
elif [ -x /usr/sbin/vpnc ]; then
	VPNC=/usr/sbin/vpnc
elif [ -x $(dirname $0)/vpnc ]; then
	VPNC=$(dirname $0)/vpnc
else
	echo No vpnc daemon found, aborting...
	exit 1
fi

for i in "$gateway" "$defr" "$pid"; do
	mkdir -p $(dirname "$i")
done

PID="$(cat "$pid" 2> /dev/null)"

if [ "$PID" ]; then
	if kill -0 "$PID" > /dev/null 2>&1; then
		echo "vpnc found running (pid: $PID, pidfile: $pid)"
		exit 1
	fi
fi

GW="$(getvar "$1" "IPSec gateway")"
if [ ! "`echo "$GW" | grep ^[[:digit:]]`" ] ; then
	if [ "`which getent`" ] ; then
		GW=`getent hosts "$GW" | sed -e 's/\ .*//'`
	elif [ "`which dig`" ] ; then
		GW=`dig "$GW" | grep "^$GW" | sed -e 's/.*\t//g'`
	elif [ "`which ping`" ] ; then
		GW=`ping "$GW" -c1 -t1| head -n1 | sed -e 's/.*(//; s/).*//'`
	else
		echo "Please enter the Gateway address as IP or install dnsutils"
		exit 1
	fi
fi

"$VPNC" --pid-file "$pid" "$1" || exit 1
ip route add $(ip route get $GW | fix_ip_get_output)
ip route | grep '^default' | fix_ip_get_output > "$defr"
echo "$GW" > "$gateway"
ip route del default
ip route add default dev $(getvar "$1" "Interface name")
ip route flush cache
exit 0
