.TH "PCF2VPNC" "1" "June 2007" "pcf2vpnc " "vpnc"
.SH "NAME"
pcf2vpnc \- converts VPN\-config files from pcf to vpnc\-format
.\"
.\" $Id$
.\"
.SH "SYNOPSIS"
.B pcf2vpnc
\fI<pcf file> \fR[\fIvpnc file\fR]
.SH "DESCRIPTION"
This script accompanies \fBvpnc\fR. It attempts to
convert *.pcf\-configuration files often spread with proprietary
(read Cisco) VPN\-clients into vpnc\-configuration files,
usually named \fB*.conf\fR.

If [\fIvpnc file\fR] is not specified, the result will be
printed to STDOUT. If specified, it will be written to that
file. Please make sure that it has appropriate permissions as
it may contain sensitive data!
.SH "AUTHOR"
pcf2vpnc was originally written by Stefan Tomanek. Updates and this man\-page were made by Wolfram Sang (ninja(at)the\-dreams.de).

Permission is granted to copy, distribute and/or modify this document under
the terms of the GNU General Public License, Version 2 any
later version published by the Free Software Foundation.
.PP
On Debian systems, the complete text of the GNU General Public
License can be found in /usr/share/common\-licenses/GPL.
.SH "SEE ALSO"
.BR vpnc(8)
.BR cisco-decrypt(8)
